// union all => 중복 있어도 다 나오게 함
// order by 전에 적어야 함

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, USER_ID,  SALES_AMOUNT
from ONLINE_SALE 
where SALES_DATE LIKE "2022-03%"
UNION ALL
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
from OFFLINE_SALE 
where SALES_DATE LIKE "2022-03%"
order by SALES_DATE, PRODUCT_ID, USER_ID