SELECT A.CAR_ID, A.CAR_TYPE, ROUND((A.DAILY_FEE *((100-C.DISCOUNT_RATE)*0.01))*30)  AS FEE
from CAR_RENTAL_COMPANY_CAR A
left join CAR_RENTAL_COMPANY_RENTAL_HISTORY B on A.CAR_ID=B.CAR_ID
left join CAR_RENTAL_COMPANY_DISCOUNT_PLAN C on A.CAR_TYPE=C.CAR_TYPE
where A.CAR_TYPE in ('세단', 'SUV') and C.DURATION_TYPE like "%30일%"
group by A.CAR_ID
having max(B.END_DATE) <= "2022-11-01"
and FEE between 500000 and 2000000
order by FEE desc, A.CAR_TYPE, A.CAR_ID desc