# 이게 level1?

SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d')
from USED_GOODS_BOARD A join USED_GOODS_REPLY B on A.BOARD_ID = B.BOARD_ID
where DATE_FORMAT(A.CREATED_DATE, '%Y-%m')  = "2022-10"
order by B.CREATED_DATE, A.TITLE