SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
from MEMBER_PROFILE A join REST_REVIEW B on A.MEMBER_ID = B.MEMBER_ID
where A.MEMBER_ID = 
(select MEMBER_ID from REST_REVIEW group by MEMBER_ID order by count(MEMBER_ID) desc LIMIT 1)
order by B.REVIEW_DATE, B.REVIEW_TEXT