SELECT YEAR(B.SALES_DATE) YEAR, MONTH(B.SALES_DATE) MONTH, A.GENDER, COUNT(DISTINCT(B.USER_ID)) USERS
from USER_INFO A join ONLINE_SALE B on A.USER_ID = B.USER_ID
where GENDER is not null
group by YEAR, MONTH, A.GENDER
order by YEAR, MONTH, A.GENDER