SELECT DISTINCT A.CAR_ID
from CAR_RENTAL_COMPANY_CAR A inner join CAR_RENTAL_COMPANY_RENTAL_HISTORY B
on A.CAR_ID = B.CAR_ID
where A.CAR_TYPE = '세단' and B.START_DATE LIKE '%2022-10%'
order by A.CAR_ID desc