SELECT YEAR(B.SALES_DATE) YEAR, MONTH(B.SALES_DATE) MONTH, COUNT(DISTINCT(B.USER_ID)) PUCHASED_USERS, ROUND(COUNT(DISTINCT(B.USER_ID))/(select count(*) from user_info where JOINED LIKE '%2021%') , 1) PUCHASED_RATIO
from USER_INFO A join ONLINE_SALE B on A.USER_ID = B.USER_ID
where A.JOINED LIKE '%2021%'
group by YEAR, MONTH
order by YEAR, MONTH