SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, sum(S.SALES* B.PRICE) TOTAL_SALES
from BOOK_SALES S join BOOK B on S.BOOK_ID = B.BOOK_ID join AUTHOR A on B.AUTHOR_ID = A.AUTHOR_ID
where S.SALES_DATE LIKE '%2022-01%'
group by A.AUTHOR_ID, B.CATEGORY
order by A.AUTHOR_ID, B.CATEGORY desc